src/App.tsx
src/components/leftSide/profile/Profile.tsx
src/components/leftSide/profile/style.tsx
src/components/rightSide/RightSide.tsx
src/components/rightSide/userList/UserList.tsx
src/components/rightSide/userList/style.tsx

- 프로필 컴포넌트 리렌더링 구현
- 오른쪽 유저리스트에 더미 데이터 생성
- 클릭한 유저 아이디에 따라 왼쪽 프로필의 state 설정
- 왼쪽 프로필에 더미 데이터 생성
- 들어오는 유저 아이디에 따라 프로필 정보 변경

feat: 프로필 컴포넌트 리렌더링 구현 #6

---

src/App.tsx
src/components/leftSide/profile/Profile.tsx
src/components/leftSide/profile/ProfileData.tsx
src/components/leftSide/profile/style.tsx
src/components/rightSide/userList/UserList.tsx
src/hooks/authReducer.ts
src/index.css
src/main.tsx
src/pages/auth/Auth.tsx
src/pages/auth/main/style.tsx
src/pages/auth/style.tsx
src/style/font.tsx

- 프로필 영역 완성 api 업데이트, 스타일
- 프로필에서 전역 username으로 쿼리 호출
- 프로필 쿼리 데이터로 렌더링
- 프로필 관계 확인하여 버튼 구현
- 프로필 스타일 구현
- 친구 리스트 더미 데이터 생성해서 버튼 렌더링 테스트
- 더미데이터 일부 프로필 쿼리로 실제 api 연동
- 오른쪽 친구 리스트에 테스트 데이터로 "아무개" 넣어두었습니다.
실제 가입한 유저네임 넣어서 테스트 하면 됩니다!
본인 프로필일 때 로그아웃, 해당 유저 클릭했을 때 [친구 추가] 버튼 뜨면 됩니다~!
- 테스트 관련 안내는 커밋메시지 및 해당 코드 주석 참고하세요~~~
- [내 프로필] 같은 버튼을 만들어서 다른 화면에서도 내 프로필 볼 수 있게끔 해야할듯?
지금은 임시로 만든거긴 한데, 계속 거기에 로그아웃 버튼을 넣는다면요!

feat: 프로필 영역 완성 api 업데이트, 스타일 #22

---

src/components/leftSide/profile/ProfileData.tsx
src/pages/NotFound.tsx
src/pages/auth/Auth.tsx
src/pages/style.tsx
src/pages/unauth/Unauth.tsx

- 왼쪽 프로필에서 로그아웃 페이지 이동 불가
- 접근 불가능한 라우터 처리
- `BrowserRouter` 위치 조정, 로그아웃 onClick 이벤트에 navigate 추가
- 존재하지 않는 라우터 NotFound 처리

fix: 왼쪽 프로필에서 로그아웃 시 페이지 이동 불가 #33

---

src/components/leftSide/profile/ProfileData.tsx
src/components/rightSide/MyProfile.tsx
src/components/rightSide/UserList.tsx

프로필에 대한 쿼리 키 일부는 profile, 일부는 user로 되어 있음
- 프로필에 대한 리액트쿼리 키 통일 (모두 profile)
- gameHistory 있는 경우 렌더링 조건 추가
- 내 프로필 언제나 온라인 (status를 실시간으로 받으려면 리패칭이 필요하나, 내 프로필은 언제나 온라인인 경우이므로!)
- login -> 온라인 / logout -> 오프라인 으로 변경
쿼리키 통일 시키려고 판 이슈인데 이것저것 추가한거라..
login/logout 외 다른 status가 추가된다면 그때 수정!

fix: react query 쿼리 키 통일 #48

---

src/components/leftSide/profile/ProfileData.tsx

- 원래 본인 프로필만 로그아웃 버튼, 나머지는 관계에 따라 친구 추가/삭제 버튼을 띄우려고 했는데 로그아웃 버튼이 어디서든 보임
- user 데이터의 `relation`에 대한 조건문 오류 수정
- 로그아웃 버튼은 본인 프로필에서만 보이게 됨

fix: user 데이터의 relation에 대한 조건문 오류 수정 #50

---

src/components/rightSide/MyProfile.tsx
src/components/rightSide/OtherUserList.tsx
src/components/rightSide/RightSide.tsx
src/components/rightSide/UserInfo.tsx
src/components/rightSide/UserList.tsx
src/components/rightSide/style.tsx
src/hooks/ProfileContext.ts
src/hooks/useInput.ts
src/pages/auth/Auth.tsx
src/pages/auth/chat/chatList/ChatList.tsx
src/pages/auth/chat/chatRoom/ChatRoom.tsx
src/pages/auth/game/gameList/GameList.tsx
src/pages/auth/game/gameRoom/GameRoom.tsx
src/pages/auth/main/Main.tsx

- 채팅방 내의 유저 목록 업데이트
- "chat" 페이지에서의 유저리스트 형태 리팩토링
- 오른쪽 컴포넌트에서 `roomId` 조회
- `inPageOf` 대신 url에서 page 조회
- 채팅방별 유저 목록 분리
- 왼쪽 프로필의 유저 context로 관리
- 방장과 admin 구분하는 아이콘 삽입
- ban 유저리스트 구현 (데이터는 소켓 이벤트 수정 후 연동 예정)
- `Auth`에서의 `setProfileUser` 함수 context로 이동
- `Auth`에서의 `inPageOf` state 삭제, 각 url로 조회
- `UserList`의 중복 내용 `UserInfo` 컴포넌트로 관리

feat: 채팅방 내의 유저 목록 업데이트 #43

---

src/components/rightSide/UserInfo.tsx
src/components/rightSide/UserList.tsx

- 이모지가 있는 경우 프로필 렌더링 오류
- username 온전하게 유지
- 이모지는 분리하여 새 prop으로 처리

fix: username과 icon 분리 #53

---

src/components/rightSide/MyProfile.tsx
src/components/rightSide/UserList.tsx
src/components/rightSide/style.tsx
src/components/rightSide/user/UserDropMenu.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/style.tsx

- 초대 알림/유저 드롭다운 메뉴 UI 구현
- `MyProfile` 내부에 알림 아이콘 삽입 (초대 있는 경우/없는 경우)
- 유저 드롭다운 메뉴 UI 구현
- `UserList` 파일이 많아져서 유저 개인에 대한 디렉토리로 user 생성

feat: 초대 알림/유저 드롭다운 메뉴 UI 구현 #59

---

src/components/rightSide/FriendAndDmBar.tsx
src/components/rightSide/OtherUserList.tsx

- 페이지마다 필요한 리스트 고려하여 재구현
- friend/dm 전체 페이지에서 조회 가능하도록 분리
- main에서의 기존 유저리스트 컴포넌트 렌더링 삭제
- 아이콘 클릭 시 조회 가능 (한 공간만 차지)
- friend/dm 리스트 메뉴바로 분리
- 제일 작업 많이한 커밋은..메인에...찍혀있습니다 다음부터 주의하겠습니다!

feat: 페이지마다 필요한 리스트 고려하여 재구현 #62 

---

src/api/user.ts
src/components/leftSide/Profile.tsx
src/components/leftSide/ProfileData.tsx
src/components/leftSide/style.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/UserList.tsx
src/components/rightSide/user/style.tsx
src/hooks/context/ProfileContext.ts
src/modal/AvatarUploadModal.tsx
src/pages/auth/Auth.tsx

- 아바타 불러오기 리액트 쿼리로 리팩토링
- 호쏭님이 리액트 쿼리로 리팩토링한 부분
+ axios 반환 blob 객체로 url 생성해서 data 리턴
- 아바타 변경 시 기존 url revoke 처리
- 프로필 사진 1:1 비율 유지하게 변경
- 파일리더 대신 `createObjectURL()` 사용해봤습니다!
- 처음엔 잘 되길래 의아했는데, 곧 "간헐적"이란 부분을 찾았습니다..아마 파일리더로 처리하는 과정에서 비동기적으로 처리되어 미완성된 파일이 나와 안되는 부분이 생긴 것 같아요

refact: getavatar react query #77

---

index.html
src/api/dm.ts
src/components/leftSide/ProfileData.tsx
src/components/leftSide/style.tsx
src/components/rightSide/FriendAndDmBar.tsx
src/components/rightSide/MyProfile.tsx
src/components/rightSide/style.tsx
src/components/rightSide/user/UserDropMenu.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/UserList.tsx
src/components/rightSide/user/style.tsx
src/hooks/useModal.tsx
src/hooks/useMouseOver.tsx
src/hooks/useOper.ts
src/hooks/useOutsideClick.tsx
src/index.css
src/main.tsx
src/modal/DmModal.tsx
src/modal/layout/ModalContainer.tsx
src/modal/layout/style.tsx
src/pages/auth/Auth.tsx
src/pages/auth/chat/list/JoinBtn.tsx
src/pages/auth/chat/list/style.tsx
src/socket/passive/friendDmListType.ts

- dm 기능 구현
- dm 리스트 구현 (REST api)
- dm 모달로 portal 사용하여 구현
- dm 전송 후 채팅 업데이트 구현
- dm 스타일 구현
- 새 dm 알림 아이콘 띄우는 로직 구현
- 모달 관련 기능 커스텀 훅으로 리팩토링
- dm 나가기 기능을 위한 아이콘 구현
- 이런저런 에러 픽스..
- dm 리스트는 rest api로 변경
- dm 나가기는 서버에서 기능 구현 끝나면 추가할 예정입니다!
- 잔에러 발생을 대비하여 여기저기 콘솔은 우선 삭제하지 않았고, 나가기까지 끝나면 삭제할게요!
- 다른 에러 수정하다 추가로 생긴 에러 : 유저 리스트가 길어져 스크롤바 생긴 경우 드롭다운 메뉴가 따라오지 않음 (해결이 어렵습니다..나중에...)
- dm 리스트가 열려있을 때 dm 보내다가 dm 모달 닫으면 dm 리스트 리페칭 시키기 (로직이 안 떠올라요..)

feat: dm 기능 구현 #76

---

src/components/leftSide/ProfileData.tsx

- 캐싱된 데이터로 인해 유저프로필 에러 발생
- 처음 생각한 수정 로직은 쿼리키에 로그인한 유저이름을 모두 작성하는 거였지만, 초기화될 때까지 일시적으로 캐싱 데이터가 늘어나는 것을 고려하여 로그아웃 시 쿼리 데이터를 reset하도록 수정

fix: 로그아웃 시 쿼리 데이터 reset #84

---

.gitignore
src/components/leftSide/AddFriendBtn.tsx
src/components/leftSide/ProfileData.tsx
src/components/rightSide/MyProfile.tsx
src/components/rightSide/user/FriendList.tsx
src/components/rightSide/user/InviteBtn.tsx
src/components/rightSide/user/UserDropMenu.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/UserList.tsx
src/hooks/useNotiModal.tsx
src/index.css
src/modal/NotificationModal.tsx
src/modal/layout/style.tsx
src/pages/auth/Auth.tsx
src/pages/auth/chat/list/JoinBtn.tsx
src/pages/auth/chat/room/ChatRoom.tsx
src/pages/auth/chat/room/Screen.tsx
src/pages/auth/chat/room/style.tsx
src/pages/unauth/signIn/style.tsx
src/pages/unauth/signUp/style.tsx
src/socket/passive/chatRoomType.ts

- 친구 추가, 리스트
- 채팅 초대, 알림
- 친구추가는 구독 방식(친구 취소 기능 x)
- 채팅초대는 채팅방 안에서 친구에게 사용하는 기능
- 해당 채팅 방에 방장, 관리자만 사용할 수 있는 기능
- 수락여부 없이 채팅에 참여
- 채팅초대되면 알림 발생 -> 알림 누르면 해당 채팅방으로 이동

feat: 친구 추가 및 채팅 초대 #79

---

src/components/rightSide/user/UserDropMenu.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/UserList.tsx
src/hooks/context/UserListContext.ts
src/hooks/useOper.ts
src/pages/auth/chat/room/ChatRoom.tsx
src/socket/passive/chatRoomType.ts

- 채팅내 사용자 block/unblock 기능 구현
- block/unblock 소켓 이벤트 연동
- 드롭메뉴 UI 구현
- 차단 대상에 대해 이모지로 표시
- 로직 테스트 완료
- [채팅방을 나가지 않고 있을 때] 차단한 순간부터 대상의 챗이 보이지 않고, 해제한 순간부터 다시 보임
- [차단하고 이탈했다 돌아오면] 차단 대상의 챗이 보이지 않음, 해제한 순간부터 이후의 챗은 보임
- [차단 대상이 퇴장했다 돌아오면] 차단 유지
- [내가 퇴장했다 돌아오면] 차단 리셋

feat: 채팅 내 사용자 block/unblock 기능 구현 #90

---

src/components/rightSide/FriendAndDmBar.tsx
src/components/rightSide/rightSideType.ts
src/components/rightSide/user/FriendList.tsx
src/components/rightSide/user/UserDropMenu.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/UserList.tsx
src/components/rightSide/user/style.tsx
src/hooks/useOper.ts
src/hooks/useOutsideClick.tsx
src/modal/DmModal.tsx
src/pages/auth/chat/room/ChatRoom.tsx
src/socket/socket.ts

- UserInfo/UserDropMenu 리팩토링
- UserDropMenu / UserInfo / UserList 리팩토링
- 타입 별도 파일로 분리
- 테스트 끝난 콘솔 로그 삭제
- 구현된 커스텀 훅 사용하여 중복 코드 삭제
- 최대한 가독성 고려하여 리팩토링 해보았습니다!!

refact: UserInfo/UserDropMenu 리팩토링 #96

---

src/components/rightSide/user/UserInfo.tsx

DM 리스트 외에서 DM 모달이 뜨지 않는 에러
- `UserInfo`의 default case에도 DM 모달 로직 삽입

fix: DM 리스트 외에서 DM 모달 안뜨는 에러 #101

---

src/components/rightSide/MyProfile.tsx
src/components/rightSide/rightSideType.ts
src/components/rightSide/user/FriendList.tsx
src/components/rightSide/user/UserDropMenu.tsx
src/components/rightSide/user/UserInfo.tsx
src/components/rightSide/user/UserList.tsx
src/hooks/useGameModal.tsx
src/hooks/useInviteGameModal.tsx
src/hooks/useNotiModal.tsx
src/modal/AcceptGameModal.tsx
src/modal/InviteGameModal.tsx
src/modal/MatchGameModal.tsx
src/modal/NotificationModal.tsx
src/modal/layout/Modal.tsx
src/modal/layout/style.tsx
src/pages/auth/Auth.tsx
src/pages/auth/game/list/GameList.tsx
src/pages/auth/game/room/GameRoom.tsx
src/pages/auth/game/room/Screen.tsx

- 게임 화면 스코어 및 결과 표시, 게임 신청 
- 게임 화면 스코어 및 결과
- 게임 나가기
- 게임 신청 모달
- 게임 신청시 알림
- 게임 신청 수락/거절 모달
- 게임 찾기 취소
- etc. 유저 상태(온라인, 오프라인 게임중) 수정, 연속 emit 방지 
- userInfo에 gameInvitationModal 추가, userDropMenu에 onInviteGameOpen추가, rightSideType 추가
- useNotiModal에 gameInvitation 이벤트 추가, notificationModal에 AcceptModal 추가
확인되는 에러는 다음 작업에 할게요~

feat: 게임 스코어 및 결과 나가기, 게임 신청 #106

---

src/@types/profile-types/profileTypes.d.ts
src/api/user.ts
src/components/leftSide/AchievementBadge.tsx
src/components/leftSide/LogoutBtn.tsx
src/components/leftSide/ProfileData.tsx
src/components/leftSide/buttons/AddFriendBtn.tsx
src/components/leftSide/buttons/LogoutBtn.tsx
src/components/leftSide/buttons/RemoveFriendBtn.tsx
src/components/leftSide/style.tsx

- 프로필 업적배지 추가 및 히스토리 업데이트
- 프로필에 업적 추가
- 업적에 따른 배지 이미지 api 및 UI 구현
- 히스토리 필요한 데이터 추가 요청 및 재명명 (score, rule)
- 히스토리 스타일 구현
- 로그아웃 시 URL로 생성한 blob URL들 revoke
- 로그아웃 버튼 컴포넌트화
- 프로필의 버튼 컴포넌트 3개 디렉토리로 분리

feat: 프로필 업적배지 추가 및 히스토리 업데이트 #109

---

src/pages/auth/game/room/Screen.tsx

- 관전용 게임결과 연동 수정, 특별 모드 연동 추가
- 관전용 게임 결과 (type:finish) 로 수정
- 특별 모드 전용 ball2 추가

fix: 관전용 게임결과 연동 수정, 특별 모드 연동 추가 #117 

---

src/components/leftSide/UserSetting.tsx

- 2차 인증이 이미 활성화된 사용자가 번호 변경 버튼을 클릭한 후
토글 클릭 시 확인 모달이 뜨지 않고 바로 토글 off됨
- `handleToggle()` 조건으로 state 대신 쿼리데이터 결과로 수정

fix: 2차인증에서 번호 변경 시 토글 바로 off되는 에러 #129

---

src/api/user.ts
src/components/leftSide/ProfileData.tsx

- 프로필 클릭할 때마다 히스토리 순서 변경되는 에러
- api 반환 직전에 `reverse()` 하고 렌더링부 코드의 `reverse()` 삭제
서버가 닫혀서 확인은 못해봤지만..

fix: 프로필 클릭할 때마다 히스토리 순서 변경되는 에러 #137
